name: CI 

on: 
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'provide version'
        required: true
        default: 'x.x.x.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: maven version
        run: mvn --version
        
      - name: Build with Maven
        run: mvn clean package

      - name: Run SonarQube Scan
        run: |
          export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          export SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}
          mvn clean install sonar:sonar \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.organization=my_organization \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
