name: CI 

on: 
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'provide version'
        required: true
        default: 'x.x.x.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean compile
