name: CI 

on: [push]
  #workflow_dispatch:
   # inputs:
    #  releaseVersion:
     #   description: 'provide version'
        #required: true
        #default: 'x.x.x.x' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Run SonarQube Scan
        run: |
          export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          export SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}
          mvn install sonar:sonar \
            -Dsonar.projectKey=scan-jpetstore \
            -Dsonar.organization=my_organization \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: maven Build
        run: |
         mvn clean package
         ls target/
      
       - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: $DOCKER_USERNAME/jpetstore-war:v1