name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  Deploy-Jpetstore-AKS:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: your-rg-name
        cluster-name: your-aks-name

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          kube/app-deploy.yaml
        images: |
          akshay87/jpetstore-war:v1
        namespace: default
